import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Examination Chat",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className="bg-gray-100 h-screen flex flex-col"
      >
        {children}
      </body>
    </html>
  );
}
